# Generated by Django 5.2.1 on 2025-05-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('habit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('activity_value_type', models.CharField(max_length=10)),
            ],
        ),
    ]
